### ISSUE TITLE
This vue app/component has no vue-meta configuration

### ISSUE THREAD

**Issue by ArosPrince** [Hernanm0g/meteor_vuetify#29]
Hi @Hernanm0g,
another (possibly Windows related issue).

I do `npm start`, wait for the app to come online and click the localhost:3000 link. I login and it directs me to the default page. So far so good. I can do anything inside that tab and it would still work.

However, if I open another tab inside the same browser and try to go again to localhost:3000 (or any other sub-route) it will never load the page, and it drops this error in the meteor console:

```
W20220113-21:11:49.532(1)? (STDERR) This vue app/component has no vue-meta configuration
W20220113-21:11:49.574(1)? (STDERR) TypeError: Cannot read property 'text' of undefined
W20220113-21:11:49.575(1)? (STDERR)     at Object.context.appendHtml (imports/startup/server/index.js:88:18)
W20220113-21:11:49.575(1)? (STDERR)     at packages/akryum:vue-ssr/server/index.js:123:82
W20220113-21:11:49.576(1)? (STDERR)     at RenderContext.done (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:9205:13)
W20220113-21:11:49.576(1)? (STDERR)     at RenderContext.next (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:2588:19)
W20220113-21:11:49.577(1)? (STDERR)     at cachedWrite (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:2451:9)
W20220113-21:11:49.577(1)? (STDERR)     at renderElement (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:8534:5)
W20220113-21:11:49.578(1)? (STDERR)     at renderNode (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:8296:5)
W20220113-21:11:49.578(1)? (STDERR)     at resolve (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:8656:7)
W20220113-21:11:49.579(1)? (STDERR)     at waitForServerPrefetch (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:8287:3)
W20220113-21:11:49.579(1)? (STDERR)     at render (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:8658:5)
W20220113-21:11:49.580(1)? (STDERR)     at Object.renderToString (F:\Projects\juran-meteor\.meteor\local\isopacks\akryum_vue-ssr\npm\node_modules\vue-server-renderer\build.dev.js:9183:9)
W20220113-21:11:49.580(1)? (STDERR)     at packages/akryum:vue-ssr/server/index.js:104:20
W20220113-21:11:49.581(1)? (STDERR)     at C:\Users\Aros\AppData\Local\.meteor\packages\promise\0.11.2\npm\node_modules\meteor-promise\fiber_pool.js:43:40
```

I do have `metaInfo` object filled in with my components, that shouldn't be a problem.

I was digging in the code and was able to find out this:

In my case filling in `metaInfo` for the root component doesn't help because the problem is with the `inject()` function itself.

At the beginning it returns the object containing the above mentioned `title`, `meta`, `style` and other objects with that `text()` function.

However, if I go to the address bar and change the route manually to some other page (or as mentioned above, just open a new tab), the `inject()` function returns an empty object, so having `metaInfo` in the root component doesn't help as that stuff will be undefined anyway.

Any ideas why would inject() return an empty object? I haven't seen this problem on my Ubuntu server, but it happens every time on my Windows dev machine.

```
    context.meta = app.$meta()

    context.appendHtml = () => {
      const {
        title,
        style,
        meta
      } = context.meta.inject() // this will return {} at some point

      return {
        head: `
          ${meta.text()}
          ${title.text()}
          <style data-vue-meta="vuetify" id="vuetify-theme-stylesheet" type="text/css" nonce="undefined"> ${vuetifyStyles}</style>
          ${style.text()}
          `
      }
```

vue-meta version is `2.4.0`

//Edit I suspect this may have something to do with this vue-meta.js code:
```
    if (!rootVm[rootConfigKey]) {
      showWarningNotSupported();
      return {};
    } // collect & aggregate all metaInfo $options
```

Which is inside the `refresh()` function.

Any ideas?

**Comment by Hernanm0g** [comment]
Hi @ArosPrince , thanks for reporting this. Ill try to reproduce this error and will be back to you with some RCA.
